name: 'Copy Directory'
description: 'Copy local directories'
author: 'Ricardo Canastro - Forked by Madara Uchiha'
inputs:
  source:
    description: 'Source path'
    required: true
  target:
    description: 'Target path'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{inputs.source}}
    - ${{inputs.target}}
branding:
  icon: 'copy'
  color: 'green'
